"""add is_deleted to invoices and external_id to customers

Revision ID: 6a93d114168a
Revises: 891658e27e27
Create Date: 2026-05-13 01:21:22.690123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a93d114168a'
down_revision: Union[str, Sequence[str], None] = '891658e27e27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('external_id', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'is_deleted')
    op.drop_column('customers', 'external_id')
    # ### end Alembic commands ###
