"""add sync_status to invoices and webhook_events table

Revision ID: 6de5e17c2c71
Revises: ad7fbaa8e94f
Create Date: 2026-05-13 10:40:41.604498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6de5e17c2c71'
down_revision: Union[str, Sequence[str], None] = 'ad7fbaa8e94f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cloudevent_id', sa.String(), nullable=True),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('external_invoice_id', sa.String(), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cloudevent_id')
    )
    op.add_column('invoices', sa.Column('sync_status', sa.String(), server_default='pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'sync_status')
    op.drop_table('webhook_events')
    # ### end Alembic commands ###
