"""add company_name to companies

Revision ID: 74ecdb0519cb
Revises: 6a93d114168a
Create Date: 2026-05-13 01:49:05.713166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74ecdb0519cb'
down_revision: Union[str, Sequence[str], None] = '6a93d114168a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('companies', sa.Column('company_name', sa.String(), nullable=False, server_default=''))
    op.alter_column('companies', 'company_name', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'company_name')
    # ### end Alembic commands ###
