"""add_event_type_to_invoice_history

Revision ID: 7c888130d208
Revises: acd2651ff6d3
Create Date: 2026-05-13 06:19:33.910945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c888130d208'
down_revision: Union[str, Sequence[str], None] = 'acd2651ff6d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_history', sa.Column('event_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_history', 'event_type')
    # ### end Alembic commands ###
