"""add origin to invoices

Revision ID: ad7fbaa8e94f
Revises: 7c888130d208
Create Date: 2026-05-13 07:30:52.064492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad7fbaa8e94f'
down_revision: Union[str, Sequence[str], None] = '7c888130d208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('origin', sa.String(), server_default='local', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'origin')
    # ### end Alembic commands ###
